sudo: required
language: csharp
dotnet: 2.0.0
mono: none
dist: trusty
env: 
  - CLI_VERSION=latest
os:
  - linux
branches:
  only:
  - master 
before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - sudo chmod 755 build.sh
script:
  - ./build.sh
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: "workout-witness"
    region: us-west-2
    skip_cleanup: true
    local_dir: release
