export const FILTER = 'FILTER';

export const WORKOUT_FETCH = 'WORKOUT_FETCH';
export const WORKOUT_CREATE = 'WORKOUT_CREATE';
export const WORKOUT_DELETE = 'WORKOUT_DELETE';

export const EXERCISE_ADD = 'EXERCISE_ADD';
export const EXERCISE_EDIT = 'EXERCISE_EDIT';
export const EXERCISE_REMOVE = 'EXERCISE_REMOVE';
export const EXERCISE_FETCH = 'EXERCISE_FETCH';


export const WORKOUTCREATOR_EDIT_WORKOUT_NAME = 'WORKOUTCREATOR_CHANGE_WORKOUT_NAME';
export const WORKOUTCREATOR_EDIT_CURRENT_EXERCISE = 'WORKOUTCREATOR_EDIT_CURRENT_EXERCISE';
export const WORKOUTCREATOR_NEXT_EXERCISE = 'WORKOUTCREATOR_NEXT_EXERCISE';
export const WORKOUTCREATOR_PREV_EXERCISE = 'WORKOUTCREATOR_PREV_EXERCISE';
export const WORKOUTCREATOR_DONE = 'WORKOUTCREATOR_DONE';