export const ADD_WORKOUT = 'ADD_WORKOUT';
export const DEL_WORKOUT = 'DEL_WORKOUT';

export const WORKOUT_CREATE_SUCCESS = 'WORKOUT_CREATE_SUCCESS';
export const WORKOUT_CREATE_FAILURE = 'WORKOUT_CREATE_FAILURE';

export const WORKOUT_ADD_EXERCISE = 'WORKOUT_ADD_EXERCISE';
export const WORKOUT_REMOVE_EXERCISE = 'WORKOUT_REMOVE_EXERCISE';
export const WORKOUT_MODIFY_EXERCISE = 'WORKOUT_MODIFY_EXERCISE';
export const WORKOUT_MODIFY_NAME = 'WORKOUT_MODIFY_NAME';
export const WORKOUT_MODIFY_DATE = 'WORKOUT_MODIFY_DATE';
